spring.application.name=task-management
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.formate_sql=true

jwt.secret=8f3Kp9vL2xQ7mN5rT1yU6wA4cD9eG2hJ7sP5zX8kB3qM6vN1